import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://goo.gl/maps/VEqhd4TKCVoXzBss9">518 Arenas!</a>
        </h1>

        <div className={styles.grid}>
          <h1>Our Favorite Subreddits:</h1>
          <a href="https://reddit.com/r/aviation" className={styles.card}>
            <h2>r/aviation &rarr;</h2>
          </a>

          <a href="https://reddit.com/r/tiktokcringe" className={styles.card}>
            <h2>r/TikTokCringe &rarr;</h2>
          </a>

          <a href="https://reddit.com/r/sandiego" className={styles.card}>
            <h2>r/SanDiego &rarr;</h2>
          </a>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
